### ISSUE TITLE
subprocess.CalledProcessError: Command 'mogrify -resize 50.0% -format png *.jpg' returned non-zero exit status 127.

### ISSUE THREAD

**Issue by yanzq95** [weiyithu/NerfingMVS#10]
After the process of depth prior training was done, a bug "/bin/sh: 1: mogrify: not found" occurred in "mogrify -resize 50.0% -format png *.jpg". How can I deal with it? Thank you!

![bug](https://user-images.githubusercontent.com/74827816/135218227-7704fdc3-da3b-42e0-9848-5d3acbb3c250.png)

**Comment by weiyithu** [comment]
I think it may be caused by the lack of imagemagick and imageio-ffmpeg dependencies. You can refer to [NeRF installation](https://github.com/bmild/nerf/blob/master/environment.yml).
