### ISSUE TITLE
Results quality of NeRF

### ISSUE THREAD

**Issue by bennyguo** [weiyithu/NerfingMVS#11]
I downloaded the results you provided and found the results of NeRF do not match the ones shown in the paper. The NeRF results in the paper seem much worse. Could you please expain what is going on here? Thanks!

**Comment by weiyithu** [comment]
We do not provide the results of original NeRF. The results in nerf folder are generated by our method without post-filtering step, i.e., the fifth line in Table 3.

**Comment by bennyguo** [comment]
Thanks for your reply!

I wonder if you could share the training setting for the original NeRF on the ScanNet dataset (results in Fig.1). Did you use the same setting as that of the LLFF data? Thank you!

**Comment by weiyithu** [comment]
Yeah, it is similar to LLFF data. However, since scannet scene is 360 captured scene, you should add --no_ndc --spherify --lindisp flags.
