### ISSUE TITLE
how to use origin pose of scannet?

### ISSUE THREAD

**Issue by chensjtu** [weiyithu/NerfingMVS#14]
thanks for your great work!, I'm trying to use the origin pose files of scannet to modify NeRFingMVS, but I encountered a pose align problem: my result is always blurred, it seems as if the pose and the radiance field is a mismatch. I wonder if you are able to solve the problem. Thanks!
![image](https://user-images.githubusercontent.com/38242929/137421139-68eca0e4-9e0e-45e0-9db2-4f701d6eea6f.png)

**Comment by weiyithu** [comment]
I think the coordinates of NeRF is aligned with COLMAP pose. You may refer to src/load_llff.py to align the coordinates with GT poses. Another solution is to use the COLMAP pose as the bridge. In other words, you can match the GT poses with COLMAP poses and then align GT poses with NeRF coordinates.

**Comment by chensjtu** [comment]
I've got it! since I change the pose to be the version of COLMAP and it looks right now, many thanks!
