### ISSUE TITLE
what is the meaning of the parameters in configs?

### ISSUE THREAD

**Issue by ycj1124** [weiyithu/NerfingMVS#16]
sorry to bother.but I wanted to try to train my own data.I download the data from the web:https://vision.middlebury.edu/mview/data/
and I found you mentioned in "Run on Your Own Data!" says factor parameter controls the resolution of output depth maps.for example ,the resolution of the  data I  download is 640*480,so what number should the "factor" be in my configs?by the way ,could you tell me what does the other parameters as follows exactly mean?
N_rand = 1024
N_samples = 64
use_viewdirs = True
raw_noise_std = 1e0
thank you very much~

**Comment by weiyithu** [comment]
The resolution of ScanNet images is 1296x968 and we use factor 2 to downsample them. I think you can use factor 1 since your image is smaller. N_rand, N_samples, use_viewdirs and raw_noise_std are the parameters of NeRF and you do not need to change them.

**Comment by ycj1124** [comment]
> The resolution of ScanNet images is 1296x968 and we use factor 2 to downsample them. I think you can use factor 1 since your image is smaller. N_rand, N_samples, use_viewdirs and raw_noise_std are the parameters of NeRF and you do not need to change them.

thank you .and do I need to prepare the depth image of each picture in image folder？ because when I run, it occurs the error called ：
Post-colmap
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    gen_poses(args.datadir)
  File "/home/ycj/NerfingMVS/utils/pose_utils.py", line 279, in gen_poses
    poses, pts3d, perm = load_colmap_data(basedir)
  File "/home/ycj/NerfingMVS/utils/pose_utils.py", line 14, in load_colmap_data
    camdata = read_model.read_cameras_binary(camerasfile)
  File "/home/ycj/NerfingMVS/utils/colmap_read_model.py", line 115, in read_cameras_binary
    with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: './data/scene0001_01/sparse/0/cameras.bin'

I check my folder and I find like this：
<img width="745" alt="001" src="https://user-images.githubusercontent.com/55937464/139689770-5bf387e6-77ad-4a3f-b4fd-8fd8a86e812a.png">
there is no depth folder and nothing in the spare folder.

**Comment by ycj1124** [comment]
> The resolution of ScanNet images is 1296x968 and we use factor 2 to downsample them. I think you can use factor 1 since your image is smaller. N_rand, N_samples, use_viewdirs and raw_noise_std are the parameters of NeRF and you do not need to change them.

and I really want to know that what part should I modify in all these .py file.because I am a beginner to the machine learning and I want to use stereo（two cameras）to make a change.I noticed that you use multi-view as a monocular depth map.how could I change if I want to use stereo？and if I want to change the model ,which of these .py code could I try to modify？sorry to bother,but I am really in a freshman class.
<img width="291" alt="002" src="https://user-images.githubusercontent.com/55937464/139691645-a32fced5-431c-4d70-911c-9f127524d7fd.png">

**Comment by weiyithu** [comment]
However, NeRF is for multi-view setting and not support to the stereo. If you only want to use stereo depth to substitute COLMAP depths, you can modify depth_priors.py accordingly. Specifically, you should change the depth in line 69 (depths, masks = load_colmap(image_list, args.datadir, args.depth_H, args.depth_W)) as your stereo depths.

**Comment by ycj1124** [comment]
> However, NeRF is for multi-view setting and not support to the stereo. If you only want to use stereo depth to substitute COLMAP depths, you can modify depth_priors.py accordingly. Specifically, you should change the depth in line 69 (depths, masks = load_colmap(image_list, args.datadir, args.depth_H, args.depth_W)) as your stereo depths.

alright ，thank very much sir. thank you again for taking up so much your  time to reply these amateur questions .I will try as your follows.thank you.

**Comment by ThePrecoder** [comment]
> > The resolution of ScanNet images is 1296x968 and we use factor 2 to downsample them. I think you can use factor 1 since your image is smaller. N_rand, N_samples, use_viewdirs and raw_noise_std are the parameters of NeRF and you do not need to change them.
> 
> thank you .and do I need to prepare the depth image of each picture in image folder？ because when I run, it occurs the error called ： Post-colmap Traceback (most recent call last): File "run.py", line 18, in gen_poses(args.datadir) File "/home/ycj/NerfingMVS/utils/pose_utils.py", line 279, in gen_poses poses, pts3d, perm = load_colmap_data(basedir) File "/home/ycj/NerfingMVS/utils/pose_utils.py", line 14, in load_colmap_data camdata = read_model.read_cameras_binary(camerasfile) File "/home/ycj/NerfingMVS/utils/colmap_read_model.py", line 115, in read_cameras_binary with open(path_to_model_file, "rb") as fid: FileNotFoundError: [Errno 2] No such file or directory: './data/scene0001_01/sparse/0/cameras.bin'
> 
> I check my folder and I find like this： <img alt="001" width="745" src="https://user-images.githubusercontent.com/55937464/139689770-5bf387e6-77ad-4a3f-b4fd-8fd8a86e812a.png"> there is no depth folder and nothing in the spare folder.

How did you handle this problem?I met it too.

**Comment by ycj1124** [comment]
sorry,I give up because I did not fix the problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weiyithu/NerfingMVS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月21日(星期二) 上午10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [weiyithu/NerfingMVS] what is the meaning of the parameters in configs? (Issue #16)





   
The resolution of ScanNet images is 1296x968 and we use factor 2 to downsample them. I think you can use factor 1 since your image is smaller. N_rand, N_samples, use_viewdirs and raw_noise_std are the parameters of NeRF and you do not need to change them.
  
thank you .and do I need to prepare the depth image of each picture in image folder？ because when I run, it occurs the error called ： Post-colmap Traceback (most recent call last): File "run.py", line 18, in gen_poses(args.datadir) File "/home/ycj/NerfingMVS/utils/pose_utils.py", line 279, in gen_poses poses, pts3d, perm = load_colmap_data(basedir) File "/home/ycj/NerfingMVS/utils/pose_utils.py", line 14, in load_colmap_data camdata = read_model.read_cameras_binary(camerasfile) File "/home/ycj/NerfingMVS/utils/colmap_read_model.py", line 115, in read_cameras_binary with open(path_to_model_file, "rb") as fid: FileNotFoundError: [Errno 2] No such file or directory: './data/scene0001_01/sparse/0/cameras.bin'
 
I check my folder and I find like this：  there is no depth folder and nothing in the spare folder.
  
How did you handle this problem?I met it too.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weiyithu** [comment]
Is there anything wrong when you run COLMAP?

**Comment by ThePrecoder** [comment]
> sorry,I give up because I did not fix the problem.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "weiyithu/NerfingMVS" ***@***.***&gt;; 发送时间:&nbsp;2021年12月21日(星期二) 上午10:55 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [weiyithu/NerfingMVS] what is the meaning of the parameters in configs? (Issue #16) The resolution of ScanNet images is 1296x968 and we use factor 2 to downsample them. I think you can use factor 1 since your image is smaller. N_rand, N_samples, use_viewdirs and raw_noise_std are the parameters of NeRF and you do not need to change them. thank you .and do I need to prepare the depth image of each picture in image folder？ because when I run, it occurs the error called ： Post-colmap Traceback (most recent call last): File "run.py", line 18, in gen_poses(args.datadir) File "/home/ycj/NerfingMVS/utils/pose_utils.py", line 279, in gen_poses poses, pts3d, perm = load_colmap_data(basedir) File "/home/ycj/NerfingMVS/utils/pose_utils.py", line 14, in load_colmap_data camdata = read_model.read_cameras_binary(camerasfile) File "/home/ycj/NerfingMVS/utils/colmap_read_model.py", line 115, in read_cameras_binary with open(path_to_model_file, "rb") as fid: FileNotFoundError: [Errno 2] No such file or directory: './data/scene0001_01/sparse/0/cameras.bin' I check my folder and I find like this： there is no depth folder and nothing in the spare folder. How did you handle this problem?I met it too. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

It happened when run demo.sh,but okay for run.sh.I solved that by this way.
