### ISSUE TITLE
Issue about install colmap

### ISSUE THREAD

**Issue by ygjwd12345** [weiyithu/NerfingMVS#22]
Hi,
I am trying to reproduce your work.
However, I face the issue about install col map.
![image](https://user-images.githubusercontent.com/32895754/147110160-d1c54f6f-42e3-4213-b685-9ced6c83231b.png)
I try to install from official web, conda and https://github.com/B1ueber2y/colmap.git.
They all fail to solve the problem. Would you mind to give me some suggestion?

**Comment by ygjwd12345** [comment]
When I use git clone https://github.com/weiyithu/NerfingMVS.git. The colmap is empty.

**Comment by ygjwd12345** [comment]
When I try use git clone --recursive git@github.com:weiyithu/NerfingMVS.git to get your colmap
the error is 
![image](https://user-images.githubusercontent.com/32895754/147113057-42e98b88-18ad-4374-992d-5aba374ac2d2.png)

**Comment by weiyithu** [comment]
I think it may be caused by your git. Do you add SSH keys?

**Comment by ygjwd12345** [comment]
thanks so much. I have successfully prepared the environment.
by using
git clone -b pointvisibility https://github.com/B1ueber2y/colmap.git

**Comment by ygjwd12345** [comment]
But I face the same problem as  #10. I will try to fix it following your suggestion.

**Comment by ygjwd12345** [comment]
For setting environment, I don't face some issue anymore.
Thanks a lot.
Have a nice holiday.

**Comment by ynma-hanvo** [comment]
> 

hi,  i do not know how to setup colmap from https://github.com/B1ueber2y/colmap.git.  as the author say:
install COLMAP in ./colmap folder (Note that do not cover colmap folder with the original version).

does it mean i clone the above git here and build it at ./colmap ?
