### ISSUE TITLE
Issue about training

### ISSUE THREAD

**Issue by ygjwd12345** [weiyithu/NerfingMVS#24]
When the training finished, I face the problem 
![image](https://user-images.githubusercontent.com/32895754/147367576-f90c2d0b-06d3-43f4-a46d-e5e070c6c29f.png)
the code stopped.

**Comment by ygjwd12345** [comment]
In detail, the code stop in p.join(). and it fails to save npy files in logs/scenesxxx/filter

**Comment by weiyithu** [comment]
I think it may be caused by multiprocessing. You may reduce 'worker_num' parameter in option.py

**Comment by ygjwd12345** [comment]
Thanks
