### ISSUE TITLE
Remove TorchsearchSorted module

### ISSUE THREAD

**Issue by DingYikang** [weiyithu/NerfingMVS#3]
Hi,
Thanks for your great work! I think you can replace the 'torchsearchsorted' module with 'torch.searchsorted()'. When I use NVIDIA GeForce RTX 2080 (same with you) to intall 'torchsearchsorted', I met some 'unsupported gpu architecture'. Maybe you can share how to install 'torchsearchsorted' on 2080 gpu with me. 
This is a nice work. Thanks!

**Comment by weiyithu** [comment]
We use https://github.com/aliutkus/torchsearchsorted to install torchsearchsorted. torchsearchsorted only appears  in run_nerf_helpers.py, which we directly copy from https://github.com/yenchenlin/nerf-pytorch. Indeed, we do not use this sample_pdf function in our method. Thus, if you have trouble installing the package, you can directly remove this function in run_nerf_helpers.py.

**Comment by DingYikang** [comment]
I use https://github.com/aliutkus/torchsearchsorted to install it, too. And I have solved this problem by repalcing this function with 'torch.searchsorted()'. I found you have not mentioned this dependcy in Readme.txt. For easy-using, maybe you can fix this part.
Thanks for your reply.

**Comment by weiyithu** [comment]
OK, I will delete sample_pdf function. Thanks for your suggestion.
