### ISSUE TITLE
About the setting of depth_W and depth_H

### ISSUE THREAD

**Issue by Beniko95J** [weiyithu/NerfingMVS#37]
Hi, I find that there is default setting of `depth_W` and `depth_H` in `options.py`. I would like to ask that if I use NerfingMVS on my custom dataset which has a totally different resolution from ScanNet, do I need to change their values or leave them not changed?

Thanks!

**Comment by weiyithu** [comment]
Yeah, you can change them according to your dataset. The larger depth_w and depth_H are, the more training and inference time you may need.
