### ISSUE TITLE
Scannet images used for training

### ISSUE THREAD

**Issue by RaresAmbrus** [weiyithu/NerfingMVS#4]
Thank you for your excellent work and for sharing the code! 

To compare with your results, can you please share which images you used for training and testing from the Scannet sequences you evaluated on?

Thanks!

**Comment by weiyithu** [comment]
Sorry, we have update README. You can acquire data from https://drive.google.com/file/d/1eY85_adVY-Z8y4XUG8mi31TJzAfdx59M/view?usp=sharing.

**Comment by RaresAmbrus** [comment]
Thank you for the quick reply and for sharing the data!
