### ISSUE TITLE
Colab notebook?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [weiyithu/NerfingMVS#7]
Thanks for sharing this fantastic work.   Would you consider releasing a Google Colab notebook for less technically inclined people like myself to to try this out?  Thanks in advance!

**Comment by weiyithu** [comment]
Hi，thanks for your attention on our work. Since our method needs online training, I think it is not convenient to use the notebook.  You may refer to run.py, which is a highly abstract of our pipeline.
