### ISSUE TITLE
struct.error: unpack requires a buffer of 12 bytes

### ISSUE THREAD

**Issue by liustu** [weiyithu/NerfingMVS#9]
There is a error about struct.error. Would you like tell me how to solve this error?thank you

**Comment by weiyithu** [comment]
I thint it may beacause you use original COLMAP instead of our version's COLMAP. Please refer to #2

**Comment by liustu** [comment]
thank you



---Original---
From: "Yi ***@***.***&gt;
Date: Sat, Sep 25, 2021 19:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [weiyithu/NerfingMVS] struct.error: unpack requires a buffer of 12 bytes (#9)




 
I thint it my beacause you use original COLMAP instead of our version's COLMAP. Please refer to #2
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
